version: '3.5'
services:
  agent:
    container_name: MTConnect_Agent
    build: .
    user: agent
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    ports: 
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    entrypoint: "/bin/sh -x /etc/MTC_Agent/docker-entrypoint.sh"
    working_dir: "/etc/MTC_Agent/"
    restart: unless-stopped
    volumes:
      - './agent.cfg:/etc/MTC_Agent/agent.cfg'
      - './Devices/:/etc/MTC_Agent/devices'
      - './Assets/:/etc/MTC_Agent/assets'
      - './Ruby/:/etc/MTC_Agent/ruby'