version: '3.5'
services:
  agent:
    container_name: MTConnect_Agent
    build: .
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    ports: 
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    entrypoint: "/bin/sh -x ./docker-entrypoint.sh"
    working_dir: "/MTC_Agent/"
    restart: unless-stopped
    volumes:
      - './agent.cfg:/MTC_Agent/agent.cfg'
      - './mtconnect-devicefiles/Devices/:/MTC_Agent/devices'
      - './mtconnect-devicefiles/Assets/:/MTC_Agent/assets'