version: '3.5'
services:
  agent:
    container_name: MTConnect_Agent
    build: .
    user: agent
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    ports: 
      - 5000:5000/tcp
      - 1883:1883/tcp
    entrypoint: "/usr/bin/mtcagent run /etc/mtconnect/data/agent.cfg"
    working_dir: "/etc/mtconnect/"
    restart: unless-stopped
    volumes:
      - './agent.cfg:/etc/mtconnect/data/agent.cfg'
      - './Devices/:/etc/mtconnect/data/devices'
      - './Assets/:/etc/mtconnect/data/assets'
      - './Ruby/:/etc/mtconnect/data/ruby'
      - './mqtt/:/etc/mosquitto'