version: '3.5'
services:
  agent:
    container_name: mtcagent
    hostname: mtcagent
    build: .
    user: agent
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    ports: 
      - 5000:5000/tcp
    entrypoint: "/usr/bin/mtcagent run /etc/mtconnect/data/agent.cfg"
    working_dir: "/etc/mtconnect/"
    restart: unless-stopped
    volumes:
      - './agent.cfg:/etc/mtconnect/data/agent.cfg'
      - './Devices/:/etc/mtconnect/data/devices'
      - './Assets/:/etc/mtconnect/data/assets'
      - './Ruby/:/etc/mtconnect/data/ruby'
    networks:
      mtc_net:
        ipv4_address: 10.5.11.2

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - "./mqtt/:/mosquitto/config"
    ports:
      - 1883:1883/tcp
    restart: unless-stopped
    networks:
      mtc_net:
        ipv4_address: 10.5.11.3

networks:
  mtc_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.11.0/29