name: Docker Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    # branches:
    # - "main"

    # Publish `2.1.2.3` tags as releases.
    tags:
      - "*.*.*.*"
  # pull_request:
  #  branches:
  #    - "main"
  # allows you to run this workflow manually from the actions tab
  # workflow_dispatch:

env:
  app: mtconnect

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            build: true
          - platform: linux/arm64
            build: false  # Set this to true if you want to build ARM64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create version
        run: |
          echo "VERSION=$(echo ${{ github.ref_name }})" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$(echo ${{ github.ref_name }} | sed -E 's/^([0-9]+)\.([0-9]+)\..+/\1.\2/')" >> $GITHUB_ENV
      - name: Build and push
        if: matrix.build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          # docker hub user/repo:tag
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mtconnect:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mtconnect:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mtconnect:${{ env.MAJOR_VERSION }}
          # push to docker hub
          push: true

      # steps:
      #   - name: Build and push Docker images
      #     uses: docker/build-push-action@v2.5.0
