name: Docker Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - "main"

    # Publish `2.1.2.3` tags as releases.
    tags:
      - "*.*.*.*"
  pull_request:
    branches:
      - "main"

env:
  app: mtconnect

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mtconnect:latest
      
      # steps:
      #   - name: Build and push Docker images
      #     uses: docker/build-push-action@v2.5.0
